version: "3.9"

services:
  api:
    # This part defines that we want our API application to be built
    build: ./api
    image: lovepreetsingh/backend-at-home-api
    ports:
      - "8080:8080"
    # Environment variables can be set as a "key: value" pair in the dictionary/mapping-system
    environment:
      PORT: 8080
  
  frontend:
    build: ./web # Build the Dockerfile from the ./web directory, relative to our directory because of the "." part
    image: lovepreetsingh/backend-at-home-frontend
    # As we are not going to surf to the frontend app, we should just "expose" instead of creating a port-mapping
    expose:
      - 5000
    environment:
    # This is an alternative syntax using a list with key=value pairs
      - Variable=Value
      - FLASK_SECRET_KEY="key"
      - JWT_SECRET_KEY="VGhpcyB3aWxsIGJ5IG15IHZlcnkgc2VjcmV0IEpXVCBrZXk="
      # Add the JWT and Secret key environments here..
    volumes:
      - nginx_statics:/app/webapp/static:rw
  nginx:
    build: ./nginx
    image: lovepreetsingh/backend-at-home-nginx
    ports:
      - "8081:80" # Choose any port you want on your 'hostPort' side. As long as the ContainerPort stays at "80"
    volumes:
      - nginx_statics:/app/static:ro

volumes:
  nginx_statics: